name: Tag Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'  # 원하는 Go 버전으로 변경하세요.

      - name: Build Go project
        run: |
          GOOS=darwin GOARCH=amd64 go build -o dft

      - name: Extract Tag Name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "${{ env.TAG_NAME }}"
          body: "Release for version ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dft
          asset_name: dft
          asset_content_type: application/x-msdownload
      
      - name: Display Release URL
        run: |
          echo "Release URL: ${{ steps.create_release.outputs.html_url }}"
      
      - name: Calculate SHA-256 Checksum
        run: |
          SHA256=$(shasum -a 256 dft | awk '{ print $1 }')
          echo "SHA-256: $SHA256"